Markup annot keys cannot contain null character
Because it's invalid for a symbol to contain 0x00.

julia> Symbol("\0")
ERROR: ArgumentError: Symbol name may not contain \0